#Deck and cards for U.S. Capitals

Deck.create(:name => "US Capitals", :difficulty => "easy", :published =>  true, :number_of_cards => 50 )
Card.create(:question => "What is the capital of Alabama?", :answer => "Montgomery", :deck_id => 1)
Card.create(:question => "What is the capital of Alaska?", :answer => "Juneau", :deck_id => 1)
Card.create(:question => "What is the capital of Arizona?", :answer => "Phoenix", :deck_id => 1)
Card.create(:question => "What is the capital of Arkansas?", :answer => "Little Rock", :deck_id => 1)
Card.create(:question => "What is the capital of California?", :answer => "Sacramento", :deck_id => 1)
Card.create(:question => "What is the capital of Colorado?", :answer => "Denver", :deck_id => 1)
Card.create(:question => "What is the capital of Connecticut?", :answer => "Hartford", :deck_id => 1)
Card.create(:question => "What is the capital of Delaware?", :answer => "Dover", :deck_id => 1)
Card.create(:question => "What is the capital of Florida?", :answer => "Tallahassee", :deck_id => 1)
Card.create(:question => "What is the capital of Georgia?", :answer => "Atlanta", :deck_id => 1)
Card.create(:question => "What is the capital of Hawaii?", :answer => "Honolulu", :deck_id => 1)
Card.create(:question => "What is the capital of Idaho?", :answer => "Boise", :deck_id => 1)
Card.create(:question => "What is the capital of Illinois?", :answer => "Springfield", :deck_id => 1)
Card.create(:question => "What is the capital of Indiana?", :answer => "Indianapolis", :deck_id => 1)
Card.create(:question => "What is the capital of Iowa?", :answer => "Des Moines", :deck_id => 1)
Card.create(:question => "What is the capital of Kansas?", :answer => "Topeka", :deck_id => 1)
Card.create(:question => "What is the capital of Kentucky?", :answer => "Frankfort", :deck_id => 1)
Card.create(:question => "What is the capital of Louisiana?", :answer => "Baton Rouge", :deck_id => 1)
Card.create(:question => "What is the capital of Maine?", :answer => "Augusta", :deck_id => 1)
Card.create(:question => "What is the capital of Maryland?", :answer => "Annapolis", :deck_id => 1)
Card.create(:question => "What is the capital of Massachusetts?", :answer => "Boston", :deck_id => 1)
Card.create(:question => "What is the capital of Michigan?", :answer => "Lansing", :deck_id => 1)
Card.create(:question => "What is the capital of Minnesota?", :answer => "Saint Paul", :deck_id => 1)
Card.create(:question => "What is the capital of Mississippi?", :answer => "Jackson", :deck_id => 1)
Card.create(:question => "What is the capital of Missouri?", :answer => "Jefferson City", :deck_id => 1)
Card.create(:question => "What is the capital of Montana?", :answer => "Helena", :deck_id => 1)
Card.create(:question => "What is the capital of Nebraska?", :answer => "Lincoln", :deck_id => 1)
Card.create(:question => "What is the capital of Nevada?", :answer => "Carson City", :deck_id => 1)
Card.create(:question => "What is the capital of New Hampshire?", :answer => "Concord", :deck_id => 1)
Card.create(:question => "What is the capital of New Jersey?", :answer => "Trenton", :deck_id => 1)
Card.create(:question => "What is the capital of New Mexico?", :answer => "Santa Fe", :deck_id => 1)
Card.create(:question => "What is the capital of New York?", :answer => "Albany", :deck_id => 1)
Card.create(:question => "What is the capital of North Carolina?", :answer => "Raleigh", :deck_id => 1)
Card.create(:question => "What is the capital of North Dakota?", :answer => "Bismarck", :deck_id => 1)
Card.create(:question => "What is the capital of Ohio?", :answer => "Columbus", :deck_id => 1)
Card.create(:question => "What is the capital of Oklahoma?", :answer => "Oklahoma City", :deck_id => 1)
Card.create(:question => "What is the capital of Oregon?", :answer => "Salem", :deck_id => 1)
Card.create(:question => "What is the capital of Pennsylvania?", :answer => "Harrisburg", :deck_id => 1)
Card.create(:question => "What is the capital of Rhode Island?", :answer => "Providence", :deck_id => 1)
Card.create(:question => "What is the capital of South Carolina?", :answer => "Columbia", :deck_id => 1)
Card.create(:question => "What is the capital of South Dakota?", :answer => "Pierre", :deck_id => 1)
Card.create(:question => "What is the capital of Tennesee?", :answer => "Nashville", :deck_id => 1)
Card.create(:question => "What is the capital of Texas?", :answer => "Austin", :deck_id => 1)
Card.create(:question => "What is the capital of Utah?", :answer => "Salt Lake City", :deck_id => 1)
Card.create(:question => "What is the capital of Vermont?", :answer => "Montpelier", :deck_id => 1)
Card.create(:question => "What is the capital of Virginia?", :answer => "Richmond", :deck_id => 1)
Card.create(:question => "What is the capital of Washington?", :answer => "Olympia", :deck_id => 1)
Card.create(:question => "What is the capital of West Virginia?", :answer => "Charleston", :deck_id => 1)
Card.create(:question => "What is the capital of Wisconsin?", :answer => "Madison", :deck_id => 1)
Card.create(:question => "What is the capital of Wyoming?", :answer => "Cheyenne", :deck_id => 1)

#Users

User.create(:name => "nate", :email=> "nate", :password => "nate", :games_played => 100, :cards_correct => 1000, :cards_shown => 1000)
